name: Generate Database Action

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 3 * *"
  workflow_dispatch:

jobs:
  generate-database:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Fetching from data.gov.hk
      run: rake build
    - name: Upload database
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
            bus.db
            bus_db.zip
            bus_db_md5.txt
          commit-msg: Upload database
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages