name: Generate Database Action

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-database:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        apt-get: libsqlite3-dev
        brew: sqlite3
        mingw: sqlite3
        vcpkg: sqlite3
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Fetching from data.gov.hk
      run: |
        bundle exec ruby main_kmb.rb
        bundle exec ruby main_nwfb_ctb.rb
        bundle exec ruby main.rb
    - name: Upload database
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
            bus.db
            bus_db.zip
            bus_db_md5.txt
          commit-msg: Upload database
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
